{{- if .Values.configService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "toskamesh.fullname" . }}-config-service
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: config-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "toskamesh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: config-service
{{- end }}
