apiVersion: apps/v1
kind: Deployment
metadata:
  name: toskamesh-core
  labels:
    app.kubernetes.io/name: toskamesh
    app.kubernetes.io/instance: toskamesh
    app.kubernetes.io/component: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: toskamesh
      app.kubernetes.io/instance: toskamesh
      app.kubernetes.io/component: core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: toskamesh
        app.kubernetes.io/instance: toskamesh
        app.kubernetes.io/component: core
      annotations:
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/includeInboundPorts: "*"
        security.istio.io/tlsMode: "istio"
    spec:
      containers:
      - name: core
        image: 192.168.50.73:5000/toskamesh-core:local-20251202-corefix
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 11111
          name: silo
          protocol: TCP
        - containerPort: 30000
          name: gateway
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ASPNETCORE_Kestrel__Endpoints__Http__Url
          value: "http://+:80"
        - name: ASPNETCORE_Kestrel__Endpoints__Https__Url
          valueFrom:
            secretKeyRef:
              name: toskamesh-mtls
              key: https_url
        - name: ASPNETCORE_Kestrel__Endpoints__Https__ClientCertificateMode
          value: "RequireCertificate"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          valueFrom:
            secretKeyRef:
              name: toskamesh-mtls
              key: server_pfx_path
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: toskamesh-mtls
              key: server_pfx_password
        - name: SSL_CERT_FILE
          value: "/etc/tls/ca.crt"
        - name: Orleans__ClusterProvider
          value: "Consul"
        - name: Orleans__ConsulAddress
          value: "http://consul-server.toskamesh-infra.svc.cluster.local:8500"
        - name: Orleans__ClusterId
          value: "talos-local"
        - name: Orleans__ServiceId
          value: "ToskaMesh-Local"
        - name: Orleans__ClusterMembership__Provider
          value: "Consul"
        - name: Mesh__ServiceDiscovery__Grpc__AllowInsecureTransport
          value: "true"
        - name: Consul__Address
          valueFrom:
            configMapKeyRef:
              name: toskamesh-core-config
              key: consul_address
        - name: ConnectionStrings__OrleansStorage
          valueFrom:
            secretKeyRef:
              name: toskamesh-core-secrets
              key: db_connection_string
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 11111
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 11111
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
        - name: mesh-tls
          mountPath: /etc/tls
          readOnly: true
      volumes:
      - name: mesh-tls
        secret:
          secretName: toskamesh-mtls
