apiVersion: v1
kind: Secret
metadata:
  name: toskamesh-core-secrets
type: Opaque
stringData:
  orleans_storage_connection: "Host=postgres;Database=toksa_mesh;Username=toksa_mesh;Password=toksa_mesh_password"
