apiVersion: v1
kind: Service
metadata:
  name: toskamesh-core
  labels:
    app: toskamesh-core
    component: core
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 11111
    targetPort: 11111
    protocol: TCP
    name: silo
  - port: 30000
    targetPort: 30000
    protocol: TCP
    name: gateway
  selector:
    app: toskamesh-core
