apiVersion: v1
kind: Service
metadata:
  name: toskamesh-core
  labels:
    app.kubernetes.io/name: toskamesh
    app.kubernetes.io/instance: toskamesh
    app.kubernetes.io/component: core
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  - port: 11111
    targetPort: 11111
    protocol: TCP
    name: silo
  - port: 30000
    targetPort: 30000
    protocol: TCP
    name: gateway
  selector:
    app.kubernetes.io/name: toskamesh
    app.kubernetes.io/instance: toskamesh
    app.kubernetes.io/component: core
