apiVersion: v1
kind: Service
metadata:
  name: adder-mesh-service
  labels:
    app: adder-mesh-service
spec:
  selector:
    app: adder-mesh-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
