apiVersion: v1
kind: Service
metadata:
  name: adder-mesh-service
  labels:
    app.kubernetes.io/name: adder-mesh-service
    app.kubernetes.io/instance: adder-mesh-service
    app.kubernetes.io/component: example
spec:
  selector:
    app.kubernetes.io/name: adder-mesh-service
    app.kubernetes.io/instance: adder-mesh-service
    app.kubernetes.io/component: example
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
