{{- if .Values.healthMonitor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "toskamesh.fullname" . }}-health-monitor-config
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: health-monitor
data:
  consul_address: {{ include "toskamesh.consul.address" . | quote }}
  discovery_grpc_address: "http://{{ include "toskamesh.fullname" . }}-discovery:80"
{{- end }}
