{{- if .Values.healthMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "toskamesh.fullname" . }}-health-monitor
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: health-monitor
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "toskamesh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: health-monitor
{{- end }}
