{{- if and .Values.authService.enabled (or (not .Values.secrets.defaultConnection.existingSecret) (not .Values.secrets.meshServiceAuth.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toskamesh.fullname" . }}-auth-service-secrets
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
type: Opaque
stringData:
  {{- if not .Values.secrets.defaultConnection.existingSecret }}
  {{ default "db_connection_string" .Values.secrets.defaultConnection.key }}: "Host={{ .Values.externalServices.postgres.host }};Database={{ .Values.externalServices.postgres.database }};Username={{ .Values.externalServices.postgres.username }};Password={{ .Values.externalServices.postgres.password }}"
  {{- end }}
  {{- if not .Values.secrets.meshServiceAuth.existingSecret }}
  {{ default "mesh_service_auth_secret" .Values.secrets.meshServiceAuth.key }}: {{ .Values.global.meshServiceAuthSecret | quote }}
  {{- end }}
{{- end }}
