apiVersion: v1
kind: Service
metadata:
  name: redis-grain-api
  namespace: toskamesh
  labels:
    app.kubernetes.io/name: redis-grain-demo
    app.kubernetes.io/instance: redis-grain-demo
    app.kubernetes.io/component: redis-grain-demo
spec:
  selector:
    app.kubernetes.io/name: redis-grain-demo
    app.kubernetes.io/instance: redis-grain-demo
    app.kubernetes.io/component: redis-grain-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
