{{- if .Values.discovery.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toskamesh.fullname" . }}-discovery-secrets
  labels:
{{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: discovery
type: Opaque
stringData:
  rabbitmq_username: {{ .Values.externalServices.rabbitmq.username | quote }}
  rabbitmq_password: {{ .Values.externalServices.rabbitmq.password | quote }}
  {{- if not .Values.secrets.meshServiceAuth.existingSecret }}
  {{ default "mesh_service_auth_secret" .Values.secrets.meshServiceAuth.key }}: {{ .Values.global.meshServiceAuthSecret | quote }}
  {{- end }}
{{- end }}
