{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toskamesh.fullname" . }}-metrics-service-secrets
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-service
type: Opaque
stringData:
  db_connection_string: "Host={{ .Values.externalServices.postgres.host }};Database={{ .Values.externalServices.postgres.database }};Username={{ .Values.externalServices.postgres.username }};Password={{ .Values.externalServices.postgres.password }}"
  mesh_service_auth_secret: {{ .Values.global.meshServiceAuthSecret | quote }}
{{- end }}
