apiVersion: v1
kind: Service
metadata:
  name: todo-mesh-silo
  labels:
    app.kubernetes.io/name: todo-mesh-silo
    app.kubernetes.io/instance: todo-mesh-silo
    app.kubernetes.io/component: example
spec:
  selector:
    app.kubernetes.io/name: todo-mesh-silo
    app.kubernetes.io/instance: todo-mesh-silo
    app.kubernetes.io/component: example
  ports:
  - name: silo
    port: 11111
    targetPort: 11111
    protocol: TCP
  - name: gateway
    port: 30000
    targetPort: 30000
    protocol: TCP
  type: ClusterIP
