apiVersion: v1
kind: ConfigMap
metadata:
  name: toskamesh-metrics-service-config
data:
  consul_address: "http://consul:8500"
  discovery_grpc_address: "https://toskamesh-internal.toskamesh.svc.cluster.local:50051"
