apiVersion: v1
kind: Service
metadata:
  name: todo-mesh-api
  labels:
    app: todo-mesh-api
    component: example
spec:
  selector:
    app: todo-mesh-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
