apiVersion: v1
kind: Service
metadata:
  name: profile-kv-store-demo
  labels:
    app.kubernetes.io/name: profile-kv-store-demo
    app.kubernetes.io/instance: profile-kv-store-demo
    app.kubernetes.io/component: example
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: profile-kv-store-demo
    app.kubernetes.io/instance: profile-kv-store-demo
    app.kubernetes.io/component: example
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
