{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "toskamesh.fullname" . }}-gateway
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "toskamesh.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        {{- include "toskamesh.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
      {{- if .Values.mesh.enabled }}
      annotations:
        {{- with .Values.mesh.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: Consul__Address
          valueFrom:
            configMapKeyRef:
              name: {{ include "toskamesh.fullname" . }}-gateway-config
              key: consul_address
        - name: Mesh__ServiceDiscovery__Grpc__Address
          valueFrom:
            configMapKeyRef:
              name: {{ include "toskamesh.fullname" . }}-gateway-config
              key: discovery_grpc_address
        - name: Jwt__SecretKey
          valueFrom:
            secretKeyRef:
              name: {{ default (printf "%s-gateway-secrets" (include "toskamesh.fullname" .)) .Values.secrets.gatewayJwt.existingSecret }}
              key: {{ default "jwt_secret_key" .Values.secrets.gatewayJwt.key }}
        resources:
          {{- toYaml .Values.gateway.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
