{{- if and .Values.gateway.enabled .Values.gateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "toskamesh.fullname" . }}-gateway
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with .Values.gateway.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ . | quote }}
  {{- end }}
spec:
  {{- if .Values.gateway.ingress.tls }}
  tls:
    {{- toYaml .Values.gateway.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.gateway.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "toskamesh.fullname" $ }}-gateway
                port:
                  number: {{ $.Values.gateway.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
