{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toskamesh.fullname" . }}-gateway-secrets
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
type: Opaque
stringData:
  jwt_secret_key: {{ .Values.gateway.secrets.jwtSecretKey | quote }}
{{- end }}
