{{- if and .Values.gateway.enabled (not .Values.secrets.gatewayJwt.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toskamesh.fullname" . }}-gateway-secrets
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
type: Opaque
stringData:
  {{ default "jwt_secret_key" .Values.secrets.gatewayJwt.key }}: {{ .Values.gateway.secrets.jwtSecretKey | quote }}
{{- end }}
