{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "toskamesh.fullname" . }}-gateway
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "toskamesh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
{{- end }}
