apiVersion: v1
kind: Secret
metadata:
  name: toskamesh-tracing-service-secrets
type: Opaque
stringData:
  db_connection_string: "Host=postgres;Database=toksa_mesh;Username=toksa_mesh;Password=toksa_mesh_password"
  mesh_service_auth_secret: "super-secret-mesh-key-change-me"
