apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-mesh-silo-config
data:
  consul_address: "http://consul-server.toskamesh-infra.svc.cluster.local:8500"
  redis_connection: "redis:6379"
  redis_database: "1"
  redis_key_prefix: "todo-mesh-silo:"
  orleans_cluster_id: "mesh-stateful"
