apiVersion: v1
kind: ConfigMap
metadata:
  name: toskamesh-discovery-config
data:
  consul_address: "http://consul-server.toskamesh-infra.svc.cluster.local:8500"
  rabbitmq_host: "rabbitmq.toskamesh-infra.svc.cluster.local"
