apiVersion: v1
kind: Secret
metadata:
  name: toskamesh-discovery-secrets
type: Opaque
stringData:
  rabbitmq_username: "guest"
  rabbitmq_password: "guest"
  mesh_service_auth_secret: "super-secret-mesh-key-change-me"
