{{- if and .Values.core.enabled (not .Values.secrets.defaultConnection.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toskamesh.fullname" . }}-core-secrets
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
type: Opaque
stringData:
  {{ default "db_connection_string" .Values.secrets.defaultConnection.key }}: "Host={{ .Values.externalServices.postgres.host }};Database={{ .Values.externalServices.postgres.database }};Username={{ .Values.externalServices.postgres.username }};Password={{ .Values.externalServices.postgres.password }}"
{{- end }}
